### ISSUE TITLE
Provide higher level recorder utilties for recording all tests in a package

### ISSUE THREAD

**Issue by dougnukem** [dnaeon/go-vcr#15]
It could be helpful to provide a higher level functionality to managing a set of recorders in a given test package.
- For example it'd be nice to inject a `Recorder` in a `TestMain()` so that all tests in a package making HTTP requests are recording/playing back requests.
- Resulting in a `httpfixtures/TestName.yml` for each `Test.*` in the package automatically
- Also we can allow for an env var to re-record tests when things change e.g. `go-vcr.mode=record`

`main_test.go`

``` go


func TestMain(m *testing.M) {
    var (
        code        = 0
        // recordMode can be specified via env var: "replay" (default) | "record" | "disabled"
        recorderMode = parseRecorderMode(os.Getenv("go-vcr.mode"))
    )

    testRecorder = recorder.NewTestRecorder(recorderMode, http.DefaultTransport)

    // inject recorder transport
    http.DefaultTransport = testRecorder.Transport()

    // Run package tests
    code = m.Run()

    // Stops the recorder and writes recorded HTTP files
    testRecorder.Stop()
    os.Exit(code)
}

func parseRecorderMode(s string) recorder.Mode {
    s = strings.ToLower(s)
    switch s {
    case "record", "recording":
        return recorder.ModeRecording
    case "replay", "replaying":
        return recorder.ModeReplaying
    case "disable", "disabled":
        return recorder.ModeDisabled
    default:
        return recorder.ModeReplaying
}


```
- The `recorder.TestRecorder` would manage a collection of `recorder.Recorder` mapped to each `Test.*` being run
  - We can use packages like `runtime/debug` to inspect stack trace for the running Test function
    - https://golang.org/pkg/runtime/debug/
- I've found it necessary in test environments to provide additional HTTP transport to inject a `X-TEST-SEQ` and match the body to ensure `POST` requests that don't have unique request params (but result in different responses)

``` go
// RoundTrip implements http round tripper
func (l *TestRecorder) RoundTrip(req *http.Request) (*http.Response, error) {

    ctxt := l.GetContext()
    transport := ctxt.recorder.Transport

    // Don't append sequence numbers for GET requests as they should return the same information (POST etc may return new response data each time called e.g. /create)
    if req.Method == http.MethodGet {
        return transport.RoundTrip(req)
    }

    seq := ctxt.NextSequence()
    req.Header.Add("X-TEST-SEQ", strconv.Itoa(seq))
    return transport.RoundTrip(req)

 }
```

``` go
httpRecorder.SetMatcher(func(r *http.Request, i cassette.Request) bool {
    if r.Method == http.MethodGet {
        return cassette.DefaultMatcher(r, i) && (reflect.DeepEqual(r.Header, i.Headers))
    }

    var b bytes.Buffer
    if _, err := b.ReadFrom(r.Body); err != nil {
        return false
    }
    r.Body = ioutil.NopCloser(&b)
    return cassette.DefaultMatcher(r, i) && (b.String() == "" || b.String() == i.Body) && (reflect.DeepEqual(r.Header, i.Headers))
})
```

**Comment by dnaeon** [comment]
Hi,

Thanks for the detailed issue!

I like this idea, would you be able to pick this one up and work on it?

Thanks,
Marin

**Comment by dougnukem** [comment]
Yep I can jump on it, worked on something similar for my company, I'll see if I can get something like that for this project.

**Comment by dnaeon** [comment]
Thanks!

**Comment by mapreal19** [comment]
@dougnukem did you give it a try?
