### ISSUE TITLE
Add a new mode: ModeRecordingOrReplaying

### ISSUE THREAD

**Issue by haibin** [dnaeon/go-vcr#20]
I'd like to have a new mode: ModeRecordingOrReplaying. It will do the recording if cassette returns ErrInteractionNotFound. Otherwise it does replaying. It is useful to me. How about others?

**Comment by mcardosos** [comment]
I would like to know the current state...
```go
if recording {
 do this
} else { // replaying
 do that
}

**Comment by c0ze** [comment]
This is definitely a useful feature. I think other implementations have this with mode `new_episodes`

**Comment by falcon78** [comment]
Is there any update on this? I would love to implement something like this myself and open a pull request if @dnaeon is ok with it

**Comment by dnaeon** [comment]
> Is there any update on this? I would love to implement something like this myself and open a pull request if @dnaeon is ok with it

Hey @falcon78 , please do ! :)

I don't have enough spare time and I will not be able to implement this myself, but would be happy to review a PR and merge it.

Thanks!

**Comment by falcon78** [comment]
@dnaeon 

Thank you for the reply, I will get started on this!

**Comment by dnaeon** [comment]
Closing this one, thanks @falcon78 !
