### ISSUE TITLE
allowing matcher to see the order of requests

### ISSUE THREAD

**Issue by spaghetty** [dnaeon/go-vcr#22]
i just hit a scenario where having the order of the requests is more useful than complex matcher.

An easy change to the matcher function adding the position in the array of the requests, allow you to check that the order of the requests is correct and use a simple matcher. 

If you are interested in this I can arrange a pull request quite easly.

**Comment by dnaeon** [comment]
@spaghetty please feel free to send any PRs. I'm not actively working on `go-vcr` anymore, but would be happy to accept your PR.

**Comment by leighmcculloch** [comment]
This would be really helpful.

**Comment by displague** [comment]
Is there any aspect of this issue that was not addressed by #37?

**Comment by dnaeon** [comment]
Hey @displague @leighmcculloch and @spaghetty ,

Been too long, but I've finally managed to get myself some time to look at some old issues.

I've just added the ID of the interaction to `v3` of `go-vcr`.

Please check out `v3` here, which should provide what you are looking for.

* https://github.com/dnaeon/go-vcr/tree/v3


Closing this one, feel free to re-open if you need anything else.

Thanks!
