### ISSUE TITLE
Gopkg.toml references etcd

### ISSUE THREAD

**Issue by leighmcculloch** [dnaeon/go-vcr#28]
The `Gopkg.toml` file references a constraint on etcd, but this package is not dependent on etcd from best I can tell and only uses etcd as an example. Could the etcd constraint be removed so that when using it doesn't get pulled in unnecessarily?

https://github.com/dnaeon/go-vcr/blob/f8a7e8b9c630b486df74145bb887793a1b85459b/Gopkg.toml#L28-L30

**Comment by dnaeon** [comment]
I've remove the dependency on `etcd` by removing the `etcd` related example, since this was the one pulling the dependency.

Should be all good now.

**Comment by leighmcculloch** [comment]
Thanks @dnaeon!!!
