### ISSUE TITLE
ContentLength is incorrectly set to 0 for HEAD requests

### ISSUE THREAD

**Issue by vangent** [dnaeon/go-vcr#30]
https://github.com/dnaeon/go-vcr/blob/master/recorder/recorder.go#L222
always sets Response.ContentLength to buf.Len(), where buf is the returned body.

Per HTTP/1.1, for HEAD requests ContentLength should be set to the size of the body that *would* have been sent for a GET: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.13.

Could this field be set based on the Content-Length header for HEAD requests? I'd be happy to send a PR.

**Comment by dnaeon** [comment]
Hey @vangent 

Thanks for reporting this! Please feel free to submit a PR, and I'd be happy to review it.

Thanks,
Marin

**Comment by vangent** [comment]
Fixed in PR #31
