### ISSUE TITLE
Throw error on realHttpTransport connection

### ISSUE THREAD

**Issue by erichulburd** [dnaeon/go-vcr#32]
Is there a way to throw an error when an HTTP connection is made on realHttpTransport during `ModeReplay`. I imagine this is up to our own implementation of `realHttpTransport` - is there a recipe we could include in the readme.md? I find this a super helpful feature of Ruby VCR.

Thanks.

**Comment by erichulburd** [comment]
It seems like the httpTransport will return `cassette.ErrInteractionNotFound` and it go swallowed somewhere in my stack.

Would you welcome a PR mentioning this in the readme? If not, I feel free to close.

**Comment by dnaeon** [comment]
Hey Eric,

Please feel free to submit a PR for this one.

Thanks,
Marin

**Comment by dnaeon** [comment]
Hey @erichulburd ,

I've started working on `v3` of `go-vcr` and with that I took the chance to refactor some of the old code, clean up the APIs, etc.

With `v3` there is a new mode of operation for the recorder -- `ModeReplayOnly`, which will never send a request over the RealTransport.

Please test it out and let me know how it goes.

I will close this one out, if you still have questions or issues, please let me know.

- https://github.com/dnaeon/go-vcr/tree/v3

Thanks!
