### ISSUE TITLE
Filter should not mutate the real response or request

### ISSUE THREAD

**Issue by rodcloutier** [dnaeon/go-vcr#40]
Currently, if you use a filter and remove a response header, the actual response header is mutated. This prevent using filter to remove sensitive data that would be returned through headers.

```
	r.AddFilter(func(i *cassette.Interaction) error {
		// This works fine, although if you inspect the request at the client level,
                // it will not have the 'X-Auth-Token' present anymore
		delete(i.Request.Headers, "X-Auth-Token")

                // This will mutate the original response object and will not pass the 'X-Subject-Token'
                // to the client
		delete(i.Response.Headers, "X-Subject-Token")
		return nil
	})
```

**Comment by lynncyrin** [comment]
Hey @rodcloutier I just ran into this too, in particular for the `Response.Body`. Did you figure out how to work around it?

**Comment by lynncyrin** [comment]
In my test the filters don't modify the request attributes (like the headers) by the do modify that `Response.Body` that's return to your code :/
