### ISSUE TITLE
interaction duration is never set

### ISSUE THREAD

**Issue by JVecsei** [dnaeon/go-vcr#62]
Hi,

I saw that there is some code to simulate the request duration ( https://github.com/dnaeon/go-vcr/blob/master/recorder/recorder.go#L234 ) but it seems this duration is not set when recording the interaction ( https://github.com/dnaeon/go-vcr/blob/master/recorder/recorder.go#L132 ).

Is there a plan on how and when this will be supported?

Thanks in advance!

**Comment by dnaeon** [comment]
@Hey @JVecsei ,

I've opened up the following PR:

* #63 

Let's use #63 to discuss this feature. Also, please test it out and let me know how it goes.
