### ISSUE TITLE
version "v2.0.0" invalid

### ISSUE THREAD

**Issue by thibaultdelor** [dnaeon/go-vcr#64]
`go-vcr` doesn't follow [V2 go modules](https://blog.golang.org/v2-go-modules)

 Doing :
```
require (
	github.com/dnaeon/go-vcr v2.0.0
)
```
Gives
```
go: errors parsing go.mod:
/Users/thibault.delor/workspace/go-search-proxy/go.mod:10:2: require github.com/dnaeon/go-vcr: version "v2.0.0" invalid: should be v0 or v1, not v2
```

I have renovate configured and its trying to use `github.com/dnaeon/go-vcr/v2 v2.0.0` which leads to 
```
go: github.com/dnaeon/go-vcr/v2@v2.0.0: go.mod has non-.../v2 module path "github.com/dnaeon/go-vcr" (and .../v2/go.mod does not exist) at revision v2.0.0
```

**Comment by dnaeon** [comment]
@thibaultdelor sorry about that.

Can you please try with `v2.0.1` ? I've just committed the `v2` structure.

**Comment by thibaultdelor** [comment]
Don't be sorry, I am using your awesome library for free!!

I just updated to v2 with no problem, thank you very much
