### ISSUE TITLE
add filter after reading the cassette

### ISSUE THREAD

**Issue by yulrizka** [dnaeon/go-vcr#67]
sometime we wants to modify the recorded values dynamically.

for example some 3rd party library generates a requestID on the HTTP header and verify it when it got the response back.

for example maybe a `ReplyFilter` can be added to give the caller a chance to modify the request or response

**Comment by dnaeon** [comment]
Hey @yulrizka ,

Can you please provide more details with probably some example code you've already got?

Thanks!

**Comment by yulrizka** [comment]
It's going to be pretty hard to create a concise example. But this test should represent what azure API go client is doing
https://github.com/Azure/azure-storage-blob-go/blob/v0.14.0/azblob/zc_policy_unique_request_id.go#L12

```
func TestCassette(t *testing.T) {
	s := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		w.Header().Set("request-id", req.Header.Get("request-id"))
	}))
	defer s.Close()

	req, _ := http.NewRequest("GET", s.URL, nil)

	rand.Seed(time.Now().UnixNano())
	reqID := strconv.Itoa(rand.Intn(10))
	req.Header.Set("request-id", reqID)

	// record
	r, err := recorder.New("fixtures/testCassette")
	require.NoError(t, err)
	defer r.Stop()

	r.SetMatcher(func(r *http.Request, i cassette.Request) bool {
		return true // http test server runs on different port each time
	})

	client := http.Client{
		Transport: r,
	}

	resp, err := client.Do(req)
	require.NoError(t, err)

	require.EqualValues(t, resp.Header.Get("request-id"), reqID)
}
```

**Comment by dnaeon** [comment]
Hey @yulrizka ,

Sorry about the long delay in getting back to you.

Why are you setting the matcher to return `true` for each interaction? This would usually match the first interaction in the cassette. Maybe I'm missing something obvious here, please explain more :)

Also, once the cassette is recorded, next time you play it will not hit the original endpoint.

Can you please explain a bit more?

Thanks!

**Comment by yulrizka** [comment]
I think the SetMatcher there is only as an example. But What I wanted to show you from the code is that: In some cases we need the ability to modify the cassette. This use case show that the az storage client generates `request-id` header and expect that header in the response. 

The cassette recording will always gives the recorded `request-id` back. This will causes invalid validation trigger on the azure client (the code i'm testing) logic. That's why a hook to modify the response would be beneficial here since I can programmatically control the response.

**Comment by dnaeon** [comment]
Hey @yulrizka ,

Got it, I think I understand now what you need. 

Please check #77 , which refactors a bit the API in regards to hooks in `go-vcr`. Using a `recorder.BeforeResponseReplayHook` hook you should be fine.
