### ISSUE TITLE
update to yaml.v3

### ISSUE THREAD

**Issue by elrayle** [dnaeon/go-vcr#71]
Are there plans to update to yaml.v3?

**Comment by elrayle** [comment]
DUP of Issue #71

**Comment by dnaeon** [comment]
Fixed in:

* https://github.com/dnaeon/go-vcr/commit/cda8081d8768dea380eec41b40c22f9e190a2c0f
* https://github.com/dnaeon/go-vcr/commit/6bd2f2d37e012291a856c69d6147a5f3cef0d218

Thanks!
