### ISSUE TITLE
Use official OSI approved license?

### ISSUE THREAD

**Issue by dhirschfeld** [dnaeon/go-vcr#86]
The current license contains custom text such that it isn't recognised by [`go-licenses`](https://github.com/google/go-licenses):
```
E0719 17:22:35.138662    3359 library.go:122] Failed to find license for gopkg.in/dnaeon/go-vcr.v3/cassette: cannot find a known open source license
E0719 17:22:35.171726    3359 library.go:122] Failed to find license for gopkg.in/dnaeon/go-vcr.v3/recorder: cannot find a known open source license
```

The text seems closest to the [`BSD-2-Clause`](https://spdx.org/licenses/BSD-2-Clause.html) license so perhaps just use that?

Other official (recognised) licenses are:
* https://spdx.org/licenses/

**Comment by dhirschfeld** [comment]
The license also isn't recognised by GitHub:

![image](https://github.com/dnaeon/go-vcr/assets/881019/21154118-da12-4abd-9637-61eb97e050ad)

**Comment by dhirschfeld** [comment]
Of course you're free to license your software however you wish, in which case, feel free to close this issue. I just opened this in case the altered text was an oversight rather than intentional.

**Comment by dnaeon** [comment]
Hey @dhirschfeld ,

The license is BSD-2-Clause, as also documented in the README.

What are the changes in it, which makes it unrecognizable?

Thanks!

**Comment by dhirschfeld** [comment]
> What are the changes in it, which makes it unrecognizable?

I opened a PR with the changes which appears to fix the identification, at least for GitHub.

I think the main issue was the extra *"in this position and unchanged"* text, though there are other minor changes e.g. `s/AUTHOR(S)/COPYRIGHT HOLDERS AND CONTRIBUTORS/`

**Comment by dnaeon** [comment]
Thanks, @dhirschfeld !
