### ISSUE TITLE
How to convert v1 cassettes format to v2 cassettes format

### ISSUE THREAD

**Issue by remyleone** [dnaeon/go-vcr#93]
Could you provide documentation about how to convert v1 cassettes format to v2? We would like to upgrade to the latest version of go-vcr but we got many cassettes in v1 format

**Comment by dnaeon** [comment]
Hey @remyleone ,

Please see: https://github.com/dnaeon/go-vcr/blob/v3/CHANGELOG.org#2021-06-24
